### ISSUE TITLE
version updating

### ISSUE THREAD

**Issue by remiMZ** [adrianjav/rotograd#1]
Hi author,
May I ask when the latest version of code can be updated? The latest version of code is related to the pseudocode below:
![image](https://user-images.githubusercontent.com/54163283/144865171-993c93d1-cb3e-4ad7-9852-19259d66f16a.png)

**Comment by adrianjav** [comment]
Hi @remiMZ,
thanks for your comment!

Indeed, the current code in this repository is outdated compared with the preprint version. I will try to update it to the current version during this incoming week, but it will be updated before the end of the month for certain.

**Comment by adrianjav** [comment]
Hi @remiMZ, I just updated the library to use the latest implementation of RotoGrad. Documentation and pip is updated as well.

I will close this issue. If you find any errors, please feel free to open a new issue,
