### ISSUE TITLE
No assignment for “self.grads”

### ISSUE THREAD

**Issue by onlyyao** [adrianjav/rotograd#4]
Thanks for your good job!
I don’t find any assignment for “self.grads” in RotateOnly so the “self.grads” remains None when running _rep_grad, is there any solution？
![2](https://user-images.githubusercontent.com/44218529/156165242-3684f427-5bd0-44af-9b7d-dfdecacfb2ff.png)

**Comment by adrianjav** [comment]
Hi @onlyyao 

`self.grads` is assigned in a backward_hook in each task-specific `RotateModule`:
https://github.com/adrianjav/rotograd/blob/7259503a996d673a108f281653d9e284b96db322/rotograd/rotograd.py#L123-L124

These `RotateModule`s are added to your architecture here:
https://github.com/adrianjav/rotograd/blob/7259503a996d673a108f281653d9e284b96db322/rotograd/rotograd.py#L197-L198

Are you using the model as described in the readme file? That is, using `preds = model(x)` to get your predictions?
